#pragma once

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CZetpathctrl1 wrapper class

class path : public CWnd
{
protected:
	DECLARE_DYNCREATE(path)
public:
	virtual BOOL Create(LPCTSTR lpszClassName, LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID, 
		CCreateContext* pContext = NULL)
	{ 
		return CreateControl( _T( "ZETPATH.ZetPathCtrl.1" ), lpszWindowName, dwStyle, rect, pParentWnd, nID); 
	}

	BOOL Create( CWnd* pParentWnd )
	{ 
		return CreateControl( _T( "ZETPATH.ZetPathCtrl.1" ), _T(""), 0, CRect( 0, 0, 0, 0 ),
			pParentWnd, 5000, NULL, FALSE, NULL );
	}

	// Attributes
public:


	// Operations
public:

	// _DZetPath

	// Functions
	//

	CString ZetPathA(BSTR * param)
	{
		CString result;
		static BYTE parms[] = VTS_PBSTR ;
		InvokeHelper(0x3, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, param);
		return result;
	}
	long ZetLetPathA(BSTR * param, BSTR * path)
	{
		long result;
		static BYTE parms[] = VTS_PBSTR VTS_PBSTR ;
		InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms, param, path);
		return result;
	}
	CString GetNextFileInDir(BSTR * dir, BSTR * file, BSTR * ext)
	{
		CString result;
		static BYTE parms[] = VTS_PBSTR VTS_PBSTR VTS_PBSTR ;
		InvokeHelper(0x5, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, dir, file, ext);
		return result;
	}
	CString ZetPathW(BSTR * param)
	{
		CString result;
		static BYTE parms[] = VTS_PBSTR ;
		InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms, param);
		return result;
	}
	long ZetLetPathW(BSTR * param, BSTR * path)
	{
		long result;
		static BYTE parms[] = VTS_PBSTR VTS_PBSTR ;
		InvokeHelper(0x7, DISPATCH_METHOD, VT_I4, (void*)&result, parms, param, path);
		return result;
	}
	long ZetSetPath(BSTR * param, BSTR * path)
	{
		long result;
		static BYTE parms[] = VTS_PBSTR VTS_PBSTR ;
		InvokeHelper(0x8, DISPATCH_METHOD, VT_I4, (void*)&result, parms, param, path);
		return result;
	}

#ifdef UNICODE
#	define ZetPath	ZetPathW
#	define ZetLetPath	ZetLetPathA
#else
#	define ZetPath	ZetPathA
#	define ZetLetPath	ZetLetPathW
#endif

	// Properties
	//



};
