// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "horscale.h"

/////////////////////////////////////////////////////////////////////////////
// CGdiplushorscalectrl1

IMPLEMENT_DYNCREATE(CHorScale, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGdiplushorscalectrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CGdiplushorscalectrl1 operations
